CQRS/Tweetter.WebUi/Controllers/TweetterController.cs
namespace Tweetter.WebUi.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.SessionState;

    using Tweetter.Domain.DataReadModel;
    using Tweetter.Domain.EntityCommands;

    [SessionState(SessionStateBehavior.ReadOnly)]
    public class TweetterController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            ViewData.Model = ServiceLocator.ReadModel.GetAllTweets();
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        } 

        [HttpPost]
        public ActionResult Create(TweetDto tweet)
        {
            try
            {
                ServiceLocator.Bus.Send(new CreateTweetCommand(tweet.Body, (Guid)this.Session["UserId"]));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var tweetDto = ServiceLocator.ReadModel.GetTweetDtolById(id);
            ViewData.Model = tweetDto;
            return View();
        }

        [HttpPost]
        public ActionResult Edit(TweetDto tweetDto)
        {
            try
            {
                var tweet = ServiceLocator.ReadModel.GetTweetDtolById(tweetDto.Id);
                ServiceLocator.Bus.Send(new ChangeTweetBodyCommand(tweetDto.Id, tweetDto.Body, tweet.Version));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CQRS/Tweetter.WebUi/Views/Tweetter/Create.cshtml
@model Tweetter.Domain.DataReadModel.TweetDto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Post new tweet.</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>TweetDto</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <p>
            <input type="submit" value="Post" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CQRS/Tweetter.WebUi/Views/Tweetter/Edit.cshtml
@model Tweetter.Domain.DataReadModel.TweetDto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Edit tweet: @Html.HiddenFor(model => model.Id)</legend>        

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CQRS/Tweetter.WebUi/Views/Tweetter/Index.cshtml
@model IEnumerable<Tweetter.Domain.DataReadModel.TweetDto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Html.ActionLink("Post new Tweet", "Create", "Tweetter")</h2>

@if (Model.Count() != 0)
{ 
    foreach (var tweet in Model)
    {
        <table>
            <tr>
                <td>
                    @tweet.Body;
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = tweet.Id })
                </td>
                <td>
                    <small>Current version: @tweet.Version</small>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    @tweet.LastDateChanged
                </td>
            </tr>
        </table>
        <br />
        <br />
    }
}
else
{ 
    <h2>There are no tweets.</h2>
}